Add color aspect info for video encoder
projectceladon/mediasdk-omx pull request #9
Opened 2021-01-07 08:07 UTC by TianmiChen

This change contains two fixes.
1. Change HEVC encoder default level from 6 to 51.
2. Add color aspect info for video encoder

Signed-off-by: Chen, Tianmi <tianmi.chen@intel.com>

2021-01-08 00:27 UTC, dyang23 commented on omx_components/src/mfx_omx_venc_component.cpp
> +        {
“{” no need.

2021-01-08 00:31 UTC, dyang23 commented on omx_components/src/mfx_omx_venc_component.cpp
> +				}
indent

2021-01-08 00:32 UTC, dyang23 commented on omx_components/src/mfx_omx_venc_component.cpp
> +           {
"{" can be removed.

2021-01-08 00:34 UTC, dyang23 commented on omx_utils/src/mfx_omx_structures.cpp
> +	{
indent issue

2021-01-08 00:36 UTC, dyang23 requested changes
Some code format issues, code logic is OK for me.

2021-01-08 01:13 UTC, LukeZheZhu approved these changes

2021-01-12 01:52 UTC, dyang23 approved these changes
Thanks for your contribution

2021-01-12 02:22 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2892

2021-01-12 02:32 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2893

2021-01-12 02:36 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2894

2021-01-12 02:42 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2895

2021-01-12 02:46 UTC, dyang23 approved these changes

2021-01-12 02:53 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2896

2021-01-12 02:59 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2897

2021-01-12 03:02 UTC, dyang23 approved these changes

2021-01-12 03:04 UTC, LukeZheZhu approved these changes

2021-01-12 03:07 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2898

2021-01-12 03:12 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2899

2021-01-12 03:13 UTC, dyang23 approved these changes

2021-01-12 03:18 UTC, dyang23 approved these changes

2021-01-12 03:21 UTC, LukeZheZhu approved these changes

2021-01-12 03:22 UTC, dyang23 approved these changes

2021-01-12 03:29 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2901

2021-01-12 07:43 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/2900

Done by "Chen, Tianmi" <tianmi.chen@intel.com>

2021-01-12 08:33 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1440

Done by "Chen, Tianmi" <tianmi.chen@intel.com>

2021-01-12 08:34 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/1441

Done by "Chen, Tianmi" <tianmi.chen@intel.com>

2021-01-12 14:28 UTC, merged

2021-01-12 14:29 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2187